{{- if not .Values.externalSecrets.app.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-ops-view.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-ops-view.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.config.server.secretKey | b64enc }}
{{- end }}

{{- if and .Values.config.oauth.enabled (not .Values.externalSecrets.oauth.enabled) }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-ops-view.fullname" . }}-oauth
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-ops-view.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.config.oauth.clientSecret | b64enc }}
{{- end }}

{{- if and .Values.redis.enabled .Values.redis.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kube-ops-view.fullname" . }}-redis
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-ops-view.redis.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.redis.password | b64enc }}
{{- end }}